# Site settings
baseurl = "sobradob.github.io/hunpednetws/"
languageCode = "en-us"
title = "HunPedNet"
theme = "hugo-freelancer-theme"
publishDir = "docs"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mr. Hugo"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    [params.navigation]
        brand = "Hungarian Pediatric Network"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.jpg"
        name = "Hungarian Pediatric Network"
        subtitle = "Medicine - Research - Children"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Services"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "HunPedNet was founded in 2016 by pediatricians experienced in pediatric clinical trials as part of the National Association of Primary Care Pediatricians (Házi Gyerek Orvosok Országos Egyesülte). The aim of the Network is to contribute to the development of Hungarian pediatric clinical studies and research. HunPedNet is strictly committed to high quality pediatric clinical trials. We take an active role in ensuring clinical studies in which minors participate are conducted in an efficient and effective manner. The network facilitates the coordination between Pharmaceutical Companies, their representatives (CROs) and independent researchers."
        right = "We facilitate participation in pediatric research and making cutting-edge pharmaceutical R&D accessible to Hungarian children. Our large patient pool, which practically covers the entire country, facilitates recruitment. Studies are carried out by paediatric practitioners and subspecialists, with a focus on epidemiological, Phase II-III-IV studies involving both healthy and sick children. We have extensive international experience working as investigators but also as sponsors (monitoring, study management) in clinical pharmacology, having recruited experts and investigators as specialists in trials and audits. We  believe in close contact to patients and their families and follow the highest ethical and professional standards."

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Kapcsolat"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["3481 Melrose Place", "Beverly Hills, CA 90210"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/spf13/hugo"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/questions/tagged/hugo"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
